spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.18:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: lab-client
          uri: lb://lab-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"